org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=2g
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true
org.gradle.isolated-projects=true
# TODO: remove when https://github.com/Kotlin/dokka/issues/4488 fix is released
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
org.jetbrains.dokka.experimental.gradle.pluginMode.nowarn=true
org.jetbrains.dokka.experimental.tryK2=true
org.jetbrains.dokka.experimental.tryK2.noWarn=true
org.jetbrains.dokka.experimental.tryK2.nowarn=true
org.jetbrains.dokka.internal.enableWorkaroundKT80551=true

kotlin.code.style=official
android.r8.maxWorkers=2
ksp.project.isolation.enabled=true
# TODO: blocked by https://youtrack.jetbrains.com/issue/KT-83410 & https://issuetracker.google.com/issues/470109449
ackpine.abiValidation.useBcv=true