name: release-tag

on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: read

jobs:
  classify:
    name: Classify pull request
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      release: ${{ steps.classify.outputs.release }}

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          ref: ${{ github.event.pull_request.base.ref }}
          persist-credentials: false

      - name: Classify pull request
        id: classify
        uses: ./.github/actions/classify-pr

  push-tag:
    runs-on: ubuntu-latest
    needs: [ classify ]
    if: github.event.pull_request.merged == true && needs.classify.outputs.release == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
          persist-credentials: false

      - name: Push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_AUTOTAG }}
          CUSTOM_TAG: ${{ github.event.pull_request.title }}
          WITH_V: false
          PRERELEASE: false