name: Setup Gradle environment
description: Sets up JDK and Gradle with caching

inputs:
  gradle-encryption-key:
    description: Gradle configuration cache encryption key.
    required: true

runs:
  using: composite

  steps:
    - name: Copy gradle.properties
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}

    - name: Cache build logic
      uses: actions/cache@v4
      with:
        path: |
          build-logic/build
          gradle/settings/build
        key: ${{ runner.os }}-build-logic-${{ hashFiles('build-logic/*.gradle*', 'build-logic/src/**', 'gradle/settings/*.gradle*', 'gradle/settings/src/**', 'gradle/*.versions.toml', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-build-logic-